<a href="https://colab.research.google.com/github/SanthoshKumarHitter/Machine-Learning/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing necessary libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

# load the dataset

In [2]:
iris = load_iris()

In [3]:
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [4]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [5]:
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = pd.DataFrame(iris.target, columns=['target'])

# split the training and testing data

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the StandardScaler

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
scaler = StandardScaler()

# Fit and transform the training data

In [11]:
X_train_scaled = scaler.fit_transform(X_train)

# Transform the testing data

In [13]:
X_test_scaled = scaler.transform(X_test)

# Initialize the KNN classifier

In [14]:
from sklearn.neighbors import KNeighborsClassifier

In [15]:
k = 3
knn_classifier = KNeighborsClassifier(n_neighbors=k)

# Train the classifier

In [16]:
knn_classifier.fit(X_train_scaled, y_train.values.ravel())

KNeighborsClassifier(n_neighbors=3)

# Predict the labels of test data

In [17]:
y_pred = knn_classifier.predict(X_test_scaled)

# Calculate accuracy

In [18]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [19]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0


# Display confusion matrix

In [21]:
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


# Display classification report

In [22]:
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

